"'Configuration List Screen' As screen":
    Height: =Max(App.Height, App.DesignHeight)
    LoadingSpinner: =LoadingSpinner.Controls
    OnVisible: |-
        =Set(
            isLoading,
            true
        );
        Set (
            MustRefreshConfigurations,
            IsEmpty(ConfigurationsCollection) || MustRefreshConfigurations;
        );
        If(
            MustRefreshConfigurations,
            // Fill-in the in-memory collection for providers
            // Using in-memory collection is needed to perform reading of lookup fields
            Refresh ('Document Automation Configurations');
            ClearCollect(
                ConfigurationsCollection,
                AddColumns(
                    Sort(
                        Filter('Document Automation Configurations', Status = 'Status (Document Automation Configurations)'.Active),
                        Name,
                        SortOrder.Ascending
                    ),
                    'Configuration State',
                    'Configuration Status',
                    Modified,
                    'Modified On'
                )
            );
            Refresh ('Document Automation Taxonomies');
            Refresh ('Document Automation Table Taxonomies');    
        );
        Set(
            MustRefreshConfigurations,
            false
        );
        // By Default, no configuration selected
        Set (
            CurrentConfiguration,
            Blank()
        );
        Set (
            CurrentConfigurationGuid,
            Blank()
        );
        Set(
            CurrentConfigurationName,
            ""
        );
        Set(
            RefreshModels,
            true
        );
        Set(
            isLoading,
            false
        );
    Orientation: =If('Configuration List Screen'.Width < 'Configuration List Screen'.Height, Layout.Vertical, Layout.Horizontal)
    Size: =1 + CountRows(App.SizeBreakpoints) - CountIf(App.SizeBreakpoints, Value >= 'Configuration List Screen'.Width)
    Width: =Max(App.Width, App.DesignWidth)

    "'Tip Rectangle_1' As rectangle":
        BorderColor: =RGBA(204, 204, 204, 1)
        BorderThickness: =1
        DisabledFill: ='Tip Rectangle_1'.Fill
        Fill: =RGBA(250, 249, 248, 1)
        FocusedBorderColor: ='Tip Rectangle_1'.BorderColor
        Height: =768
        HoverFill: ='Tip Rectangle_1'.Fill
        PressedFill: ='Tip Rectangle_1'.Fill
        Width: =269.00
        X: =1097.00
        ZIndex: =1

    "'Documentation Button' As button":
        BorderColor: =ColorFade('Documentation Button'.Fill, -15%)
        Fill: =RGBA(116, 39, 116, 1)
        FocusedBorderColor: ='Documentation Button'.BorderColor
        Font: =Font.'Segoe UI'
        FontWeight: =FontWeight.Normal
        Height: =32
        HoverBorderColor: =ColorFade('Documentation Button'.BorderColor, 20%)
        PaddingRight: =5.00
        PaddingTop: =5.00
        PressedBorderColor: ='Documentation Button'.Fill
        PressedColor: ='Documentation Button'.Fill
        PressedFill: ='Documentation Button'.Color
        RadiusBottomLeft: =1
        RadiusBottomRight: =1
        RadiusTopLeft: =1
        RadiusTopRight: =1
        Size: =12.00
        Text: ="Learn more"
        Visible: =false
        Width: =140.00
        X: =1161.00
        Y: =693
        ZIndex: =2

    "'Tip Label' As label":
        Align: =LayoutAlignItems.Center
        FocusedBorderColor: ='Tip Label'.BorderColor
        Font: =Font.'Segoe UI'
        Height: =99
        HoverBorderColor: ='Tip Label'.BorderColor
        HoverColor: ='Tip Label'.Color
        HoverFill: ='Tip Label'.Fill
        PaddingRight: =5.00
        PaddingTop: =5.00
        PressedBorderColor: ='Tip Label'.BorderColor
        PressedColor: ='Tip Label'.Color
        PressedFill: ='Tip Label'.Fill
        Size: =12.00
        Text: |-
            ="Choose the AI Builder model to use to start processing documents automatically.
            "
        Width: =214.00
        X: =1124.00
        Y: =430
        ZIndex: =3

    "'Tip Title' As label":
        Align: =LayoutAlignItems.Center
        FocusedBorderColor: ='Tip Title'.BorderColor
        Font: =Font.'Segoe UI'
        FontWeight: =FontWeight.Semibold
        Height: =51
        HoverBorderColor: ='Tip Title'.BorderColor
        HoverColor: ='Tip Title'.Color
        HoverFill: ='Tip Title'.Fill
        PaddingRight: =5.00
        PaddingTop: =5.00
        PressedBorderColor: ='Tip Title'.BorderColor
        PressedColor: ='Tip Title'.Color
        PressedFill: ='Tip Title'.Fill
        Size: =12.00
        Text: ="Create a configuration"
        Width: =177.00
        X: =1143.01
        Y: =380
        ZIndex: =4

    "'Tip Image' As image":
        FocusedBorderColor: ='Tip Image'.BorderColor
        Height: =128
        HoverBorderColor: =ColorFade('Tip Image'.BorderColor, 20%)
        HoverFill: =ColorFade('Tip Image'.Fill, 20%)
        Image: =CreateProvider
        PaddingRight: =0.00
        PaddingTop: =0.00
        PressedBorderColor: =ColorFade('Tip Image'.BorderColor, -20%)
        PressedFill: =ColorFade('Tip Image'.Fill, -20%)
        Width: =166.00
        X: =1142.00
        Y: =271
        ZIndex: =5

    "'Configurations List' As dataTable.datatable":
        BorderColor: =RGBA(237, 237, 237, 1)
        BorderStyle: =BorderStyle.Solid
        BorderThickness: =1
        Color: =RGBA(96, 94, 92, 1)
        DisplayMode: =DisplayMode.Edit
        Fill: =RGBA(0, 0, 0, 0)
        Font: =Font.'Segoe UI'
        HeadingColor: =RGBA(50, 49, 48, 1)
        HeadingFill: =RGBA(255, 255, 255, 1)
        HeadingFont: =Font.'Segoe UI'
        HeadingSize: =12
        Height: =569
        HoverColor: =RGBA(96, 94, 92, 1)
        HoverFill: =RGBA(237, 235, 233, 1)
        Items: =ConfigurationsCollection
        NoDataText: ="We didn't find any data to show at this time. Create a Forms Processing model first."
        SelectedColor: =RGBA(96, 94, 92, 1)
        SelectedFill: =RGBA(225, 223, 221, 1)
        Size: =12.00
        Visible: =true
        Width: =1034.00
        X: =24.00
        Y: =176
        ZIndex: =6

        "'Modified On_Column' As dataTableColumn.dateTimeColumn":
            AutoWidth: =false
            DisplayMode: =DisplayMode.Edit
            FieldDisplayName: ="Modified on"
            FieldName: ="modifiedon"
            FieldVariantName: ="dateTimeColumn"
            Height: =Parent.Height
            LayoutHeight: =Parent.Height
            OnSelect: =true
            Order: =7
            Text: =Text(ThisItem.'Modified On',DateTimeFormat.ShortDate)
            Width: =119.99
            X: =0.00
            Y: =0
            ZIndex: =4

        "'Created By_Column' As dataTableColumn.complexTypeColumn":
            AutoWidth: =false
            DisplayMode: =DisplayMode.Edit
            FieldDisplayName: ="Created By"
            FieldName: ="createdby"
            FieldVariantName: ="complexTypeColumn"
            Height: =Parent.Height
            LayoutHeight: =Parent.Height
            Order: =10
            Text: =ThisItem.'Created By'.firstname & " " & ThisItem.'Created By'.lastname
            Width: =235.00
            X: =597.01
            Y: =0
            ZIndex: =12

        Name_Column As dataTableColumn.textualColumn:
            AutoWidth: =false
            DisplayMode: =DisplayMode.Edit
            FieldDisplayName: ="Name"
            FieldName: ="aib_name"
            FieldVariantName: ="textualColumn"
            Height: =Parent.Height
            IsHyperlink: =true
            LayoutHeight: =Parent.Height
            OnSelect: |-
                =Set(
                    CurrentConfigurationGuid,
                    'Configurations List'.Selected.'Document Automation Configuration'
                );
                Set(
                    CurrentConfigurationName,
                    'Configurations List'.Selected.Name
                );
                Navigate('Model Selection Screen')
            Order: =4
            Text: =ThisItem.Name
            Width: =464.00
            X: =0.00
            Y: =0
            ZIndex: =16

        "'Configuration State_Column1' As dataTableColumn.textualColumn":
            DisplayMode: =DisplayMode.Edit
            FieldDisplayName: ="Status"
            FieldName: ="Configuration State"
            FieldVariantName: ="textualColumn"
            Height: =Parent.Height
            LayoutHeight: =Parent.Height
            Order: =17
            Text: =ThisItem.'Configuration State'
            Width: =100.00
            X: =0.00
            Y: =0
            ZIndex: =22

    "'Provider List Rectangle' As rectangle":
        BorderColor: =RGBA(204, 204, 204, 1)
        BorderThickness: =0.2
        DisabledFill: ='Provider List Rectangle'.Fill
        Fill: =RGBA(0, 0, 0, 0)
        FocusedBorderColor: ='Provider List Rectangle'.BorderColor
        Height: =40
        HoverFill: ='Provider List Rectangle'.Fill
        PressedFill: ='Provider List Rectangle'.Fill
        Width: =1034.00
        X: =24.00
        Y: =135
        ZIndex: =7

    "'Add Provider Button' As button":
        BorderColor: =ButtonStandard.BorderColor
        BorderThickness: =ButtonStandard.BorderThickness
        Color: =RGBA(0, 0, 0, 1)
        Fill: =RGBA(255, 255, 255, 1)
        FocusedBorderColor: =ButtonStandard.FocusedBorderColor
        FocusedBorderThickness: =ButtonStandard.FocusedBorderThickness
        Font: =Font.'Segoe UI'
        FontWeight: =FontWeight.Normal
        Height: =32
        HoverBorderColor: =ButtonStandard.HoverBorderColor
        HoverColor: =ButtonStandard.HoverColor
        HoverFill: =ButtonStandard.HoverFill
        OnSelect: |-
            =// Remove provider data in memory
            Set (
                CurrentConfigurationGuid,
                Blank()
            );
            Set(
                CurrentConfigurationName,
                ""
            );
            Set(
                ConfigurationModelGuid,
                Blank()
            );
            Set(
                ConfigurationModelName,
                ""
            );
            // Go to wizard
            Navigate('Model Selection Screen')
        PaddingRight: =5.00
        PaddingTop: =5.00
        PressedBorderColor: =ButtonStandard.PressedBorderColor
        PressedColor: =ButtonStandard.PressedColor
        PressedFill: =ButtonStandard.PressedFill
        RadiusBottomLeft: =ButtonStandard.BorderRadius
        RadiusBottomRight: =
        RadiusTopLeft: =ButtonStandard.BorderRadius
        RadiusTopRight: =
        Size: =12.00
        Text: ="Add configuration"
        Visible: =CountRows(ConfigurationsCollection)=0
        Width: =180.00
        X: =874.00
        Y: =140
        ZIndex: =8

    "'Selected Tab Line_1' As rectangle":
        DisabledFill: ='Selected Tab Line_1'.Fill
        Fill: =RGBA(116, 39, 116, 1)
        FocusedBorderColor: ='Selected Tab Line_1'.BorderColor
        Height: =2
        HoverFill: ='Selected Tab Line_1'.Fill
        PressedFill: ='Selected Tab Line_1'.Fill
        Width: =119.99
        X: =154.99
        Y: =110
        ZIndex: =11

    "'Providers Tab Label_1' As label":
        Align: =Align.Center
        FocusedBorderColor: ='Providers Tab Label_1'.BorderColor
        Font: =Font.'Segoe UI'
        FontWeight: =FontWeight.Semibold
        Height: =25
        HoverBorderColor: ='Providers Tab Label_1'.BorderColor
        HoverColor: ='Providers Tab Label_1'.Color
        HoverFill: ='Providers Tab Label_1'.Fill
        PaddingBottom: =0
        PaddingLeft: =0
        PaddingRight: =0.00
        PaddingTop: =0.00
        PressedBorderColor: ='Providers Tab Label_1'.BorderColor
        PressedColor: ='Providers Tab Label_1'.Color
        PressedFill: ='Providers Tab Label_1'.Fill
        Size: =14.00
        Text: ="Configuration"
        Width: =140.00
        X: =145.00
        Y: =84
        ZIndex: =12

    "'Invoices Tab Button_1' As button":
        AutoDisableOnSelect: =false
        BorderColor: =ColorFade('Invoices Tab Button_1'.Fill, -15%)
        BorderThickness: =0
        Color: =RGBA(0, 0, 0, 1)
        Fill: =RGBA(255, 255, 255, 1)
        FocusedBorderColor: ='Invoices Tab Button_1'.BorderColor
        FocusedBorderThickness: =0
        Font: =Font.'Segoe UI'
        FontWeight: =FontWeight.Normal
        Height: =25
        HoverBorderColor: =RGBA(255, 255, 255, 1)
        HoverColor: =RGBA(0, 0, 0, 1)
        HoverFill: =
        OnSelect: =Navigate('Document List Screen')
        PaddingBottom: =0
        PaddingLeft: =0
        PaddingRight: =0.00
        PaddingTop: =0.00
        PressedBorderColor: =
        PressedColor: =RGBA(0, 0, 0, 1)
        PressedFill: =RGBA(255, 255, 255, 1)
        Size: =14.00
        Text: ="Documents"
        Width: =95.00
        X: =24.00
        Y: =84
        ZIndex: =13

    "'Provider List Title' As label":
        FocusedBorderColor: ='Provider List Title'.BorderColor
        Font: =Font.'Segoe UI'
        FontWeight: =FontWeight.Semibold
        Height: =30
        HoverBorderColor: ='Provider List Title'.BorderColor
        HoverColor: ='Provider List Title'.Color
        HoverFill: ='Provider List Title'.Fill
        PaddingBottom: =0
        PaddingLeft: =0
        PaddingRight: =0.00
        PaddingTop: =0.00
        PressedBorderColor: ='Provider List Title'.BorderColor
        PressedColor: ='Provider List Title'.Color
        PressedFill: ='Provider List Title'.Fill
        Size: =17.99
        Text: ="Document Processing"
        Width: =1000.00
        X: =24.00
        Y: =24
        ZIndex: =14

    "'Loading Glass Pane_2' As rectangle":
        BorderColor: =RGBA(204, 204, 204, 1)
        BorderThickness: =1
        DisabledFill: ='Loading Glass Pane_2'.Fill
        Fill: =RGBA(0, 0, 0, 0.02)
        FocusedBorderColor: ='Loading Glass Pane_2'.BorderColor
        Height: =768
        HoverFill: ='Loading Glass Pane_2'.Fill
        PressedFill: ='Loading Glass Pane_2'.Fill
        Visible: =isLoading
        Width: =1366.00
        X: =0.00
        ZIndex: =15

    "'Configuration Tab Button_4' As button":
        AutoDisableOnSelect: =false
        BorderColor: =ColorFade('Configuration Tab Button_4'.Fill, -15%)
        BorderThickness: =0
        Color: =RGBA(0, 0, 0, 1)
        Fill: =RGBA(255, 255, 255, 1)
        FocusedBorderColor: ='Configuration Tab Button_4'.BorderColor
        FocusedBorderThickness: =0
        Font: =Font.'Segoe UI'
        FontWeight: =FontWeight.Normal
        Height: =27
        HoverBorderColor: =RGBA(255, 255, 255, 1)
        HoverColor: =RGBA(0, 0, 0, 1)
        HoverFill: =
        OnSelect: =Navigate('File Upload Screen')
        PaddingBottom: =0
        PaddingLeft: =0
        PaddingRight: =0.00
        PaddingTop: =0.00
        PressedBorderColor: =
        PressedColor: =RGBA(0, 0, 0, 1)
        PressedFill: =RGBA(255, 255, 255, 1)
        Size: =14.00
        Text: ="Upload"
        Visible: =IsPowerUser
        Width: =121
        X: =290
        Y: =85
        ZIndex: =16

